site_name: OC-Accel Doc
repo_name: GitHub
repo_url: https://github.com/OpenCAPI/oc-accel-doc
edit_uri: ""  

nav:
  - About:
    - 'Overview': 'index.md'
    - 'About the repository': 'repository.md'
    - 'System Firmware Setup': 'system_firmware_setup.md'
  - User Guide:
          - '(0) Steps in a glance': 'user-guide/0-steps.md'
          - '(1) Prepare environment': 'user-guide/1-prepare-env.md'
          - '(2) Run helloworld': 'user-guide/2-run-helloworld.md'
          - '(3) Create a new action': 'user-guide/3-new-action.md'
          - '(4) Verilog/VHDL design': 'user-guide/4-hdl-design.md'
          - '(5) HLS C++ design': 'user-guide/5-hls-design.md'
          - '(6) Co-Simulation': 'user-guide/6-co-simulation.md'
          - '(7) Build image': 'user-guide/7-build-image.md'
          - '(8) Deploy on Power Server': 'user-guide/8-deploy.md'
          - '(9) Migrate from SNAP1/2': 'user-guide/9-migrate.md'
          - '(10) Tips': 'user-guide/10-tips.md'
  - Examples:
    - 'hdl_example': 'actions-doc/hdl_example.md'
    - 'hdl_single_engine': 'actions-doc/hdl_single_engine.md'
    - 'hls_helloworld_512': 'actions-doc/hls_helloworld_512.md'
    - 'hls_helloworld_1024': 'actions-doc/hls_helloworld_1024.md'
    - 'hls_memcopy_512' : 'actions-doc/hls_memcopy_512.md'
    - 'hls_memcopy_1024': 'actions-doc/hls_memcopy_1024.md'
    - 'hls_hbm_memcopy_1024': 'actions-doc/hls_hbm_memcopy_1024.md'
    - 'hls_image_filter': 'actions-doc/hls_image_filter.md'
    - 'hls_helloworld_python': 'actions-doc/hls_helloworld_python.md'
    - 'hls_decimal_mult': 'actions-doc/hls_decimal_mult.md'

  - Deep Dive:
    - 'Software API': 'deep-dive/software-api.md'
    - 'Registers': 'deep-dive/registers.md'
    - 'Hardware Logic': 'deep-dive/hardware-logic.md'
    - 'New Board Support': 'deep-dive/board-package.md'
  - Appl. Notes:
    - 'OC-AD9V3 installation in AC922': 'apps_notes/Installing_an_OC-AD9V3_on_AC922.md'
    - 'OC-AD9H7 installation in IC922': 'apps_notes/Installing_an_OC-AD9H7_on_IC922.md'
  - Misc:
    - 'Document Guide': 'misc/doc-guide.md'
theme:
  name: mkdocs 
# Code block colors: Dark
#  hljs_style: hybrid
#  hljs_style: monokai
#  hljs_style: tomorrow-night
#  hljs_style: railscasts
# Code block colors: Light
#  hljs_style: googlecode
#  hljs_style: solarized-light
  hljs_style: github
#  hljs_style: foundation

extra_css:
  - extra.css

extra_javascript:
  - extra.js

markdown_extensions:
  - admonition
